import { createGridCollection, createListCollection } from "@chakra-ui/react";

export const cities = [
  { label: "Casablanca", value: "casablanca" },
  { label: "Marrakech", value: "marrakech" },
  { label: "Kenitra", value: "kenitra" },
  { label: "Mohammedia", value: "mohammedia" },
  { label: "Salé", value: "sale" },
  { label: "Tanger", value: "tanger" },
  { label: "Rabat", value: "rabat" },
]

export const neighborhoodsByCity: { [key: string]: string[] } = {
  casablanca: [
    "2 Mars",
    "Abdelmoumen",
    "Aïn Borja",
    "Aïn Chock",
    "Aïn Diab",
    "Ain Sebaa",
    "Al Batha",
    "Al Fida",
    "Al Madina Aljadida",
    "Almaz",
    "Al Mostakbal",
    "Al Qods",
    "Alsace Lorraine",
    "Anfa",
    "Autre secteur",
    "Bachkou",
    "Beauséjour",
    "Belvédère",
    "Ben Ejdia",
    "Ben M'sick",
    "Bourgogne",
    "Bournazil",
    "Californie",
    "Casablanca Finance City",
    "Centre Ville",
    "C.I.L",
    "Derb Ghallef",
    "Derb Omar",
    "El Manar El Hank",
    "Errahma",
    "Ferme Bretone",
    "Florida",
    "Fonciere",
    "Franceville",
    "Gauthier",
    "Habous",
    "Hay Al Amal",
    "Hay Albaraka",
    "Hay Alfalah",
    "Hay Almassira 1",
    "Hay Almassira 2",
    "Hay Almassira 3",
    "Hay Chrifa",
    "Hay El Farah",
    "Hay Hana",
    "Hay Hassani",
    "Hay Inara",
    "Hay Laymouna",
    "Hay Mansour",
    "Hay M'barka",
    "Hay Mohammadi",
    "Hay Moulay Rachid",
    "Hay Moulay Rachid 1",
    "Hay Moulay Rachid 2",
    "Hay Moulay Rachid 3",
    "Hay Moulay Rachid 4",
    "Hay Moulay Rachid 5",
    "Hay Moulay Rachid 6",
    "Hay Rajaa",
    "Hay Sadri",
    "Hay Tarik",
    "Hermitage",
    "Hippodrome",
    "Hôrloge",
    "Industriel Nord",
    "La Gare",
    "La Gironde",
    "Laimoune",
    "Les Camps",
    "Les Cretes",
    "Les Princesses",
    "Lissasfa",
    "Longchamps",
    "Lusitania",
    "Maarif",
    "Maârif Extension",
    "Mandarona",
    "Marina",
    "Mers Sultan",
    "Moulay Youssef",
    "Nassim",
    "Oasis",
    "Oulfa",
    "Palmier",
    "Parc",
    "Polo",
    "Quartier des Hôpitaux",
    "Racine",
    "Riviera",
    "Roches Noires",
    "Route d'Azemmour",
    "Route d'El Jadida",
    "Sbata",
    "Sidi Belyout",
    "Sidi Bernoussi",
    "Sidi Maarouf",
    "Sidi Moumen",
    "Sidi Othmane",
    "Sour Jdid",
    "Tantonville",
    "Triangle d'Or",
    "Val d'Anfa",
    "Val Fleuri",
    "Zone Industrielle",
    "Zone Industrielle Moulay Rachid"
  ],
  marrakech: [
    "Afaq",
    "Agdal",
    "Ain Mezouar",
    "Akioud",
    "Allal El Fassi",
    "Amelkis",
    "Amerchich",
    "Ancienne Médina",
    "Annakhil",
    "Arset Ben Chebli"
  ],
  kenitra: [
    "Ain Sebaa",
    "Al Alama",
    "Al Baladya",
    "alliance",
    "Al Maghrib Al Arabi",
    "Assam",
    "Autre secteur",
    "Bab Fès",
    "Bir Anzarane",
    "Bir Rami",
    "Bir Rami Est",
    "Bir Rami Industriel",
    "Bir Rami Ouest",
    "Centre",
    "Corcica",
    "Diour 10000",
    "Diour Sniak",
    "El Assam",
    "El Haddada",
    "El Haouzia",
    "El Ismailia",
    "El Menzah",
    "Fouarate",
    "Inara",
    "kasbat al mahdia",
    "Khabazat",
    "La Base",
    "La Cigogne",
    "La Cité",
    "La Ville Haute",
    "Maamora",
    "Mellah",
    "Mimosas",
    "Ouled Arfa",
    "Ouled M'Barek",
    "Ouled Oujih",
    "PAM",
    "Quartier Al Fath",
    "quartier golf",
    "Quartier Nahda",
    "Saknia",
    "Seyad",
    "Taïbia",
    "Val Fleury",
    "Village"
  ],
  mohammedia: [
    "Al Qods",
    "Amal",
    "Autre secteur",
    "Belle Vue",
    "Centre Ville",
    "Corniche",
    "Derb Bouchman",
    "Derb Jamila",
    "Derb Lfath",
    "Derb Marrakech",
    "Derb Meknes",
    "Derb Rbat",
    "Diour Dokala",
    "Diour Lakrai",
    "Diour Nicolas",
    "El Alia",
    "El Bradaa",
    "El Kasbah",
    "Hassania 1",
    "Hassania 2",
    "Hassania 3",
    "Hay Al Amal",
    "Hay Al Falah",
    "Hay Al Horria",
    "Hay Al Wahda",
    "Hay Annasr",
    "Hay Chabab",
    "Hay Essalama",
    "Hay Mesk Lil",
    "Hay saada",
    "Hay Salam",
    "Kasbah",
    "La Colline",
    "La Siesta",
    "Les Cretes",
    "L'habitat",
    "Mimosas",
    "Monica",
    "Nassim",
    "Partie Est",
    "Port",
    "Quartier du Parc",
    "Quartier Du Soleil",
    "Rachidia",
    "Riad 1",
    "Riad 2",
    "Tenoukchet",
    "Wafa",
    "Yassmine",
    "Zone industrielle"
  ],
  sale: [
    "Salé",
    "Abouab Sala",
    "Al Bassatine",
    "Al Mouahidine",
    "Al Moukataa",
    "Andalouss",
    "Annaim",
    "Bab Al Bahr",
    "Bab Sebta",
    "Bettana",
    "Bled El Gharbi",
    "Cherkaoui - Marzouka",
    "Cité Militaire",
    "Dar El Lhamra",
    "Dyour El ghaba",
    "Dyour Nejjar",
    "El Qaria",
    "Frougui",
    "Ghrablia",
    "Hay Alqods",
    "Hay Cheikh Lamfadel",
    "Hay Chmaou",
    "Hay Inbiat",
    "Hay Karima",
    "Hay Moulay Ismail",
    "Hay Oued Dahab",
    "Hay Rahma",
    "Hay Salam",
    "Horria",
    "Inbiaat",
    "Kharouba",
    "Lakhmis",
    "Lalla Aicha",
    "Lharya",
    "Medina",
    "Mkinssia",
    "Omar",
    "Ouled Moussa",
    "Pépinière",
    "Roustal",
    "Said Hajji",
    "Sakani",
    "Sala El Jadida",
    "Sidi Abdellah",
    "Sidi Moussa",
    "Tabriquet",
    "Technopolis",
    "Zone Industrielle Hay Arrahma",
    "Zone Industrielle Saniat Sbihi"
  ],
  tanger: [
    "Achakar",
    "Achennad",
    "Administratif",
    "Ahammar",
    "Aharrarine",
    "Ahlane",
    "Aida",
    "Ain El Hayani",
    "ain zaitouna",
    "Al Amal",
    "Al Anbar",
    "Algerie",
    "Alia",
    "Al Irfane 2",
    "Al Kasaba",
    "Al Mandar Al Jamil",
    "Al Warda",
    "Aouama Gharbia",
    "Autre secteur",
    "Aviation",
    "Azib Haj Kaddour",
    "Beausejour",
    "Behair",
    "Bel Air - Val fleuri",
    "Ben Dibane",
    "Beni Makada Lakdima",
    "Beni Said",
    "Beni Touzine",
    "Benkirane",
    "Bir Aharchoune",
    "Bir Chairi",
    "Bir Chifa",
    "Bir El Ghazi",
    "Bouchta-Abdelatif",
    "Bouhout 1",
    "Bouhout 2",
    "Boukhalef",
    "Branes 1",
    "Branes 2",
    "Branes Kdima",
    "Californie",
    "Cap spartel",
    "Casabarata",
    "Castilla",
    "Centre",
    "Centre ville",
    "Charf",
    "Cité californie",
    "Dar Zhiro",
    "De La Plage",
    "Dher Ahjjam",
    "Dher Lahmam",
    "Draoua",
    "Drissia",
    "Du Golf",
    "El Baraka",
    "El Haj El Mokhtar",
    "El Khair 1",
    "El Khair 2",
    "El Majd",
    "El Mers 1",
    "El Mers 2",
    "El Mrabet",
    "El Oued",
    "Ennasr",
    "Girari",
    "Gourziana",
    "Haddad",
    "Hanaa 1",
    "Hanaa 2",
    "Hanaa 3 - Soussi",
    "Hay Al Bassatine",
    "Hay El Boughaz",
    "Hay Hassani",
    "Hay Zaoudia",
    "Iberie",
    "Ibn Taymia",
    "Jbel Kbir",
    "Jirrari",
    "Laaouina",
    "Lalla Chafia",
    "la Nouvelle Ville Ibn Battouta",
    "Les Rosiers",
    "Makhoukha",
    "Malabata",
    "manar",
    "Marchan",
    "Marchane",
    "Marjane",
    "Médina",
    "Mediouna",
    "Mesnana",
    "Mghayer",
    "Mghogha",
    "Mister Khouch",
    "M'nar",
    "Moujahidine",
    "Moulay Youssef",
    "Mozart",
    "Msala",
    "M'sallah",
    "nouinouich",
    "Nzaha",
    "Port Tanger ville",
    "Rmilat",
    "Sania",
    "Santa",
    "Souani",
    "Star Hill",
    "Tanger City Center",
    "Tanja Balia",
    "Val Fleuri",
    "Vieille montagne",
    "Zemmouri",
    "Ziatene",
    "Zone Industrielle Mghogha",
    "Zouitina"
  ],
  rabat: [
    "Aakkari",
    "Abi Ragrag",
    "Agdal",
    "Al Irfane",
    "Autre secteur",
    "Aviation",
    "Aviation - Mabella",
    "Diour Jamaa",
    "Douar el Hajja",
    "El Youssoufia",
    "Guich Oudaya",
    "Hassan",
    "Haut Agdal",
    "Hay Al Farah",
    "Hay Arrachad",
    "Hay el Fath",
    "Hay Nahda",
    "Hay Riad",
    "Kébibat",
    "Les Ambassadeurs",
    "Les Orangers",
    "Les Oudayas",
    "Mabella",
    "Massira",
    "Mechouar",
    "Médina de Rabat",
    "Quartier de l'Océan",
    "Riyad",
    "Riyad Extension",
    "Souissi",
    "Taqaddoum",
    "Yacoub El Mansour"
  ]
};

export const citiesCollection = createListCollection({
  items: cities.map((city) => ({ label: city.label, value: city.value }))
});

export function getNeighborhoodsCollection(cityValue: string) {
  const neighborhoods = neighborhoodsByCity[cityValue] || [];
  return neighborhoods.map((neighborhood) => ({
    label: neighborhood,
    value: neighborhood.toLowerCase().replace(/\s+/g, '_')
  }));
}