export const PROPERTYICONS = {
    transactionType: "icon-park-solid:transaction",
    price: "solar:tag-price-bold",
    totalArea: "lsicon:measure-outline",
    bedrooms: "material-symbols:bed-outline",
    bathrooms: "solar:bath-line-duotone",
    parkingSpaces: "iconoir:car",
    isFurnished: "mdi:sofa",
    city: "ion:location-outline",
    buildingAge: "lucide:building",
    orientation: "mdi:compass-outline",
    floorNumber: "bi:building",
    syndicateFees: "material-symbols:concierge-outline",
    hasBasement: "lsicon:park-outline",
    hasSecurity: "fluent:video-security-24-regular" , 
    hasBalcony: "iconoir:balcony",
    hasTerrace: "hugeicons:terrace",
    hasElevator: "material-symbols-light:elevator-outline",
    hasAirConditioning: "cbi:air-conditioner",
    hasPool: "cil:pool",
    hasEquippedKitchen: "emojione-monotone:kitchen-knife",
    hasEasyAccess: "mdi:wheelchair",
    hasGarden: "maki:garden",
    hasOceanView: "mdi:ocean",
}