// src/app/[locale]/layout.tsx
import type { Metadata } from 'next';
import { ReactNode } from 'react';

import { NextIntlClientProvider } from 'next-intl';
import { getMessages, setRequestLocale } from 'next-intl/server';

import { locales, type Locale } from '@/i18n/locales';
import { cormorant_garamond, display } from '@/theme/fonts';
import './globals.css';
import { Provider } from '@/components/ui/provider';
import { Box } from '@chakra-ui/react';
import { Footer, Navbar } from '@/components/layout';

export const metadata: Metadata = {
  title: 'Majestic Keys',
  description: 'Generated by create next app'
};

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params
}: {
  children: ReactNode;
  params: Promise<{ locale: Locale }>;
}) {
  const { locale } = await params;
  setRequestLocale(locale);
  const messages = await getMessages();
  return (
    <html lang={locale} suppressHydrationWarning className={cormorant_garamond.variable}>
      <body className={cormorant_garamond.variable}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Provider>
            <Navbar />
            <Box minH="calc(100vh)" bg="brand.500">
              {children}
            </Box>
            <Footer />
          </Provider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
